name: gpu_env
channels:
  - conda-forge # Canal comunitario (siempre actualizado)
  - nvidia # Canal oficial de Nvidia (opcional, pero útil para drivers nuevos)
dependencies:
  - python=3.11 # Numba funciona muy bien con 3.10 o 3.11
  - pip
  # Librerías fundamentales
  - numpy
  - numba

  # EL SECRETO: Instalar el toolkit aquí
  - cudatoolkit # Provee las librerías necesarias para que Numba hable con la GPU

  # Opcional pero RECOMENDADO si usas GPU:
  - cupy # Es como NumPy pero corre en la GPU (muy compatible con Numba)

  # Herramientas de desarrollo
  - jupyterlab
  - ipykernel
